//
// Created by brand on 12/23/2017.
//

#ifndef CSTRUCTURES_CSTRUCTURES_CONFIG_H
#define CSTRUCTURES_CSTRUCTURES_CONFIG_H

#define CSTRUCTURES_GLOBAL_RESIZE_ENABLE 1

#endif //CSTRUCTURES_CSTRUCTURES_CONFIG_H
